name = "Bladpack"
author = "begbaj"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e3937c8d46504aec2c5751fdfccfcbcb8b16b6682391903487e9b3bf498d77e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"

[options]
acceptable-game-versions = ["1.21.1"]
