name = "Bladpack"
author = "begbaj"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4a99602a15a5e3244071bb9d65742f55f755752357ade79c415ac725baa2e84"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
