version = 1
enableSodiumMenu = true
cloudCulling = false
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
fluidtank = true
mekanismadditions = true
merequester = true
powah = true
travelersbackpack = true
twilightforest = true
aether = true
ae2 = true
mekanismgenerators = true
industrialforegoing = true
waystones = true
mekanism = true
toughasnails = true
toms_trading_network = true
visualworkbench = true
sereneseasons = true
pipez = true
minecraft = true
