name = "Bladpack"
author = "begbaj"
version = "0.2.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d20103882ab27f997174af2a494e291bd8c7d52495ab3ec6f23d844b20fa956"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"

[options]
acceptable-game-versions = ["1.21.1"]
