name = "Bladpack"
author = "begbaj"
version = "0.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca42f789806e709e156b6436430b092157fd75db6f8c5abad14784f50c48c309"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"

[options]
acceptable-game-versions = ["1.21.1"]
